version: "3.1"
services:
  webserver:
    container_name: webserver
    image: nginx:mainline-alpine
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/backend.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
      - dhparam:/etc/ssl/certs
    networks:
      - docker-network
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email ksichien@posteo.net --agree-tos --no-eff-email --force-renewal -d api.dashofoats.xyz
    networks:
      - docker-network
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/backend
    networks:
      - docker-network
  database:
    container_name: dashofoats_db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/home/root/data/db
    networks:
      - docker-network
volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/dash-of-oats/web-root/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/dash-of-oats/dhparam/
      o: bind
networks:
  docker-network:
    driver: bridge
